src/FairPlayTubeSln/FairPlayTube.Client/CustomValidators/UploadVideoModelValidator.cs
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Upload.razor
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Upload.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/_Imports.razor
src/FairPlayTubeSln/FairPlayTube.Client/wwwroot/index.html
src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoInfo.cs
src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/VideoInfo.sql
src/FairPlayTubeSln/FairPlayTube.Models/Video/UploadVideoModel.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs

Adding custom validator
Solves Github Issue #

Adding ability to upload from URL

---

src/FairPlayTubeSln/FairPlayTube.Client/ClientServices/UserProfileClientService.cs
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Profile/Monetization.razor
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Profile/Monetization.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/Program.cs
src/FairPlayTubeSln/FairPlayTube.Client/Shared/NavMenu.razor
src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.csproj
src/FairPlayTubeSln/FairPlayTube.Models/UserProfile/GlobalMonetizationModel.cs
src/FairPlayTubeSln/FairPlayTube/Controllers/UserProfileController.cs

Adding global monetization links logic
Solves Github Issue #48

Adding Global Monetization maintenance

---

src/FairPlayTubeSln/FairPlayTube.Models/Video/GlobalKeywordModel.cs
src/FairPlayTubeSln/FairPlayTube.Services/BackgroundServices/VideoIndexStatusService.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
src/FairPlayTubeSln/FairPlayTube/Controllers/VideoController.cs

Encoding video idnexer params
Solves Github Issue #51

Adding keywords endpoint.

---

src/FairPlayTubeSln/FairPlayTube.Client/Shared/LoginDisplay.razor
src/FairPlayTubeSln/FairPlayTube.Client/Shared/MainLayout.razor

Adding Azure QnA bot

---

src/FairPlayTubeSln/FairPlayTube/FairPlayTube.csproj
src/FairPlayTubeSln/FairPlayTube/Startup.cs
src/FairPlayTubeSln/FairPlayTube/Swagger/Filters/SecurityRequirementsOperationFilter.cs

Enabling swagger support

---

src/FairPlayTubeSln/FairPlayTube/FairPlayTube.csproj
src/FairPlayTubeSln/FairPlayTube/Properties/launchSettings.json

Setting up project to run on mac

---

src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor
src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor.cs
src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoInfoModel.cs

it was added video description and the icon in the insights section
https://github.com/efonsecab/FairPlayTube/issues/41

Video Description

---

src/FairPlayTubeSln/FairPlayTube.Client/CustomComponents/SignalR/NotificationHub.razor
src/FairPlayTubeSln/FairPlayTube.Client/CustomComponents/SignalR/NotificationHub.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/FairPlayTube.Client.csproj
src/FairPlayTubeSln/FairPlayTube.Client/Shared/MainLayout.razor
src/FairPlayTubeSln/FairPlayTube.Client/Shared/NavMenu.razor
src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
src/FairPlayTubeSln/FairPlayTube.Models/Notifications/NotificationModel.cs
src/FairPlayTubeSln/FairPlayTube/Controllers/AzureVideoIndexerController.cs
src/FairPlayTubeSln/FairPlayTube/Notifications/Hubs/INotificationHub.cs
src/FairPlayTubeSln/FairPlayTube/Notifications/Hubs/NotificationHub.cs
src/FairPlayTubeSln/FairPlayTube/Startup.cs

Adding base implementation for SignalR
Solves Github Issue #71

Adding base for supporting SignalR

---

src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
src/FairPlayTubeSln/FairPlayTube.Models/UserProfile/UserModel.cs
src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/UserControllerTests.cs
src/FairPlayTubeSln/FairPlayTube/Controllers/UserController.cs

Adding a new endpoint to list users
Solves Github Issue #79

Adding endpoint to list users

---

src/FairPlayTubeSln/FairPlayTube.Models/Invites/InviteUserModel.cs
src/FairPlayTubeSln/FairPlayTube.Services/Configuration/SmtpConfiguration.cs
src/FairPlayTubeSln/FairPlayTube.Services/EmailService.cs
src/FairPlayTubeSln/FairPlayTube/Controllers/UserController.cs
src/FairPlayTubeSln/FairPlayTube/Startup.cs

Implementation of EmailService
Solves Github Issue #83

Adding EmailService

---

src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor

Fixes displaying of videos in mobile devices
Solves Github Issue #44

Fixing display on mobile devices

---

src/FairPlayTubeSln/FairPlayTube.Client/ClientServices/UserProfileClientService.cs
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/List.razor
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/List.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/Shared/NavMenu.razor
src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
src/FairPlayTubeSln/FairPlayTubeSln.sln

UsersPage Added

---

src/FairPlayTubeSln/FairPlayTube.Models/UserMessage/UserMessageModel.cs
src/FairPlayTubeSln/FairPlayTube/Controllers/UserController.cs

SendMessage Endpoint Created
The endpoint will insert the message in the UserMessage table.
After the changes have been saved, the user is notified.
Resolves #82

SendMessage Endpoint Created

---

src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs

Sets default sorting
Solves Github Issue #92

Setting default sorting to newest videos first

---

src/FairPlayTubeSln/FairPlayTube.Client/wwwroot/index.html

Adding mailchimp popup

---

src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Upload.razor
src/FairPlayTubeSln/FairPlayTube.Client/_Imports.razor
src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
src/FairPlayTubeSln/FairPlayTube.Components/FairPlayTube.Components.csproj
src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor
src/FairPlayTubeSln/FairPlayTube.Components/_Imports.razor
src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.csproj
src/FairPlayTubeSln/FairPlayTube.Models/Video/UploadVideoModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoInfoModel.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs

Enabling the UI fields for Video's Price.
Solves Github Issue #112

Enabling fields to set and display a video's price

---

src/FairPlayTubeSln/FairPlayTube.Models/Video/UpdateVideoModel.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
src/FairPlayTubeSln/FairPlayTube/Controllers/VideoController.cs

Adding endpoint and service method to update a video's price
Solves Github Issue #114

Adding endpoint to allow updating owned video

---

src/FairPlayTubeSln/FairPlayTube.Client/ClientServices/VideoClientService.cs
src/FairPlayTubeSln/FairPlayTube.Client/CustomComponents/Videos/EditVideo.razor
src/FairPlayTubeSln/FairPlayTube.Client/CustomComponents/Videos/EditVideo.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Details.razor
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Details.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/_Imports.razor
src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
src/FairPlayTubeSln/FairPlayTube.Components/_Imports.razor
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
src/FairPlayTubeSln/FairPlayTube/Controllers/VideoController.cs

Adding UI to edit video's price
Solves Github Issue #117

Adding UI to edit video

---

src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/VideoControllerTests.cs
src/FairPlayTubeSln/FairPlayTube/Controllers/VideoController.cs

Adding endpoint to Buy a video's access.
Adding test.
Solves Github Issue #121

Adding BuyVideoAccess endpoint and test

---

src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor

Fixing videos width
Adds the buy video access icon
Solves Github Issue #123

Adding BuyVideoAccess icon

---

src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs

Fixing code to reflect change in user's available funds
Solves Github Issue #122

adding logic to reflect change i nfunds

---

src/FairPlayTubeSln/FairPlayTube.Client/wwwroot/Index.Development.html
src/FairPlayTubeSln/FairPlayTube.Client/wwwroot/index.html
src/FairPlayTubeSln/FairPlayTube.Client/wwwroot/js/azure/video-indexer/vb.widgets.mediator.js

Adding custom video indexer mediator script
Solves Github Issue #94

Adding custom video indexer mediator script

---

src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoStatusModel.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
src/FairPlayTubeSln/FairPlayTube/Controllers/VideoController.cs

Adding endpoint to get a user's pending videos status
Solves Github Issue #139

Adding the "GetMyPendingVideosQueue" endpoint

---

src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/MyPendingVideosStatus.razor
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/MyPendingVideosStatus.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/Shared/NavMenu.razor
src/FairPlayTubeSln/FairPlayTube.ClientServices/VideoClientService.cs
src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs

Adding page to check pending videos status
Solves Github Issue #141

Adding page to check pending videos status

---

src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoJob.partial.cs
src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoJobModel.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs

Adding the "AddVideoJobAsync" method
Solves Github Issue #147

Creating the "AddVideoJobAsync" method

---

src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
src/FairPlayTubeSln/FairPlayTube/Controllers/VideoController.cs

Adding the "AddVideoJob" endpoint
Solves Github Issue #149

Adding the AddVideoJob endpoint

---

src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor
src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoInfoModel.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
src/FairPlayTubeSln/FairPlayTube/AutoMapperProfiles/GlobalMappingProfile.cs

Add the number of available jobs to the ToolTip
Solves Github Issue #151

Adding the number of Available Jobs

---

src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor
src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoInfoModel.cs
src/FairPlayTubeSln/FairPlayTube/AutoMapperProfiles/GlobalMappingProfile.cs

Enhancing the tooltip message
Solves Github Issue #153

Enhancing the "Available Jobs" tooltip message

---

src/FairPlayTubeSln/FairPlayTube.ClientServices/VideoClientService.cs

Adding the client method to buy video access
Solves Github Issue #161

Adding the BuyVideoAccessAsync method to VideoClientService

---

src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/UserMessage.cs
src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/UserMessage.partial.cs
src/FairPlayTubeSln/FairPlayTube.DataAccess/efpt.config.json
src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/UserMessage.sql

It was added the OriginatorInfo interface columns to the table
https://github.com/efonsecab/FairPlayTube/issues/29

it was implemented the methods from OriginatorInfo

---

src/FairPlayTubeSln/FairPlayTube.Models/Persons/PersonModel.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs

Adding the "GetAllPersonsAsync" method
Solves Github Issue #173

Adding the "GetAllPersonsAsync" method to the VideoService class

---

src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/Person.cs
src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/Person.sql
src/FairPlayTubeSln/FairPlayTube.Models/Persons/PersonModel.cs
src/FairPlayTubeSln/FairPlayTube.Services/BackgroundServices/VideoIndexStatusService.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs

Adding logic to persist faces
Solves Github Issue #177

Adding logic to persist persons and sample faces picture

---

src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs

Adding the "GetPersistedPersonsAsync" method
Solves Github Issue #179

Adding the "GetPersistedPersonsAsync" method

---

src/FairPlayTubeSln/FairPlayTube.Models/Persons/PersonModel.cs
src/FairPlayTubeSln/FairPlayTube/AutoMapperProfiles/GlobalMappingProfile.cs
src/FairPlayTubeSln/FairPlayTube/Controllers/VideoController.cs

Adding "GetPersons" endpoint
Solves Github Issue #181

Adding GetPersons endpoint

---

src/FairPlayTubeSln/FairPlayTube.Client/FairPlayTube.Client.csproj
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Persons.razor
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Persons.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/Shared/NavMenu.razor
src/FairPlayTubeSln/FairPlayTube.ClientServices/VideoClientService.cs
src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
src/FairPlayTubeSln/FairPlayTube/Controllers/VideoController.cs

Adding the "GetPersons" endpoint client, and the Persons page
Solves Github Issue #183

Adding GetPersons Client and persons page

---

src/FairPlayTubeSln/FairPlayTube.Client/FairPlayTube.Client.csproj
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Index.razor
src/FairPlayTubeSln/FairPlayTube.ClientServices/FairPlayTube.ClientServices.csproj
src/FairPlayTubeSln/FairPlayTube.Common/FairPlayTube.Common.csproj
src/FairPlayTubeSln/FairPlayTube.Components/FairPlayTube.Components.csproj
src/FairPlayTubeSln/FairPlayTube.DataAccess/FairPlayTube.DataAccess.csproj
src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.sqlproj
src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.csproj
src/FairPlayTubeSln/FairPlayTube.Notifications/FairPlayTube.Notifications.csproj
src/FairPlayTubeSln/FairPlayTube.Services/FairPlayTube.Services.csproj
src/FairPlayTubeSln/FairPlayTube.SystemConfigurator/FairPlayTube.SystemConfigurator.csproj
src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/VideoControllerTests.cs
src/FairPlayTubeSln/FairPlayTube.Tests/FairPlayTube.Tests.csproj
src/FairPlayTubeSln/FairPlayTube.Tests/TestsBase.cs
src/FairPlayTubeSln/FairPlayTube.VideoIndexer/FairPlayTube.VideoIndexer.csproj
src/FairPlayTubeSln/FairPlayTube/FairPlayTube.csproj

Forcing all projects to treat warnings as errors
Solves Github Issue #190

Setting projects to treat warnings as errors

---

src/FairPlayTubeSln/FairPlayTube.Models/CustomHttpResponse/ProblemHttpResponse.cs
src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.csproj
src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.xml
src/FairPlayTubeSln/FairPlayTube.Models/Invites/InviteUserModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/Notifications/NotificationModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/Paypal/PaypalCheckoutApprovedDataModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/Paypal/PaypalCheckoutApprovedDetailsModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/Persons/PersonModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/UserMessage/UserMessageModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/UserProfile/GlobalMonetizationModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/UserProfile/UserModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/UserProfile/UserProfileModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/Video/GlobalKeywordModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/Video/UpdateVideoModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/Video/UploadVideoModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoInfoModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoJobModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoStatusModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/VisitorTracking/VisitorTrackingModel.cs

Enable the documentation on the models project
Solves Github Issue #192

Enabling Xml Documentation for the Models project

---

src/FairPlayTubeSln/FairPlayTube/AutoMapperProfiles/GlobalMappingProfile.cs
src/FairPlayTubeSln/FairPlayTube/Controllers/AzureVideoIndexerController.cs
src/FairPlayTubeSln/FairPlayTube/Controllers/UserController.cs
src/FairPlayTubeSln/FairPlayTube/Controllers/UserProfileController.cs
src/FairPlayTubeSln/FairPlayTube/Controllers/VideoController.cs
src/FairPlayTubeSln/FairPlayTube/Controllers/VisitorTrackingController.cs
src/FairPlayTubeSln/FairPlayTube/CustomProviders/CurrentUserProvider.cs
src/FairPlayTubeSln/FairPlayTube/FairPlayTube.csproj
src/FairPlayTubeSln/FairPlayTube/FairPlayTube.xml
src/FairPlayTubeSln/FairPlayTube/Pages/Error.cshtml.cs
src/FairPlayTubeSln/FairPlayTube/Program.cs
src/FairPlayTubeSln/FairPlayTube/Startup.cs
src/FairPlayTubeSln/FairPlayTube/Swagger/Filters/SecurityRequirementsOperationFilter.cs

Enables Xml doc generation and swagger docs from xml comments
Solves Github Issue #194

Enable server project documentation

---

src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Upload.razor
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Upload.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/_Imports.razor
src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoInfo.cs
src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.refactorlog
src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/VideoInfo.sql
src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.xml
src/FairPlayTubeSln/FairPlayTube.Models/Video/UploadVideoModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoInfoModel.cs
src/FairPlayTubeSln/FairPlayTube.Services/BackgroundServices/VideoIndexStatusService.cs
src/FairPlayTubeSln/FairPlayTube.Services/FairPlayTube.Services.csproj
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs

Enabling Language selection when uploading a video
Solves Github Issue #196

Enabling language selection on upload

---

src/FairPlayTubeSln/FairPlayTube.Services/FairPlayTube.Services.csproj
src/FairPlayTubeSln/FairPlayTube.Services/MessageService.cs
src/FairPlayTubeSln/FairPlayTube/Controllers/UserController.cs
src/FairPlayTubeSln/FairPlayTube/FairPlayTube.xml
src/FairPlayTubeSln/FairPlayTube/Startup.cs

Moving code to a service and enabled content moderation
Solves Github Issue #212

Creating message service

---

src/FairPlayTubeSln/FairPlayTube/Startup.cs

Enabling services
Solves Github Issue #212

Adding services configuration

---

src/FairPlayTubeSln/FairPlayTube.Services/ContentModerationService.cs
src/FairPlayTubeSln/FairPlayTube.Services/FairPlayTube.Services.csproj
src/FairPlayTubeSln/FairPlayTube.Services/MessageService.cs
src/FairPlayTubeSln/FairPlayTube/Startup.cs

Updating package.
Moving content moderation to its own service class
Solves Github Issue #215

Allow language detection on content moderation

---

src/FairPlayTubeSln/FairPlayTube.Services/FairPlayTube.Services.csproj
src/FairPlayTubeSln/FairPlayTube.Services/TextAnalysisServices.cs
src/FairPlayTubeSln/FairPlayTube/Startup.cs

Implementing the base for the service
Solves Github Issue #218

Enabling Text Analysis Service

---

src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoCommentAnalysis.cs
src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/VideoCommentAnalysis.sql
src/FairPlayTubeSln/FairPlayTube.Services/TextAnalysisServices.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs

Adding "AnalyzeVideoCommentAsync"
Removing columns not required anymore
Fixing Sentiment column type
Solves Github Issue #221

Adding "AnalyzeVideoCommentAsync" method.

---

src/FairPlayTubeSln/FairPlayTube/Controllers/VideoController.cs
src/FairPlayTubeSln/FairPlayTube/FairPlayTube.xml

Adding the "AnalyzeVideoComment" endpoint
Solves Github Issue #223

Adding the "AnalyzeVideoComment" endpoint

---

src/FairPlayTubeSln/FairPlayTube.Client/wwwroot/js/azure/video-indexer/vb.widgets.mediator.js
src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor
src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor.cs
src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoInfo.cs
src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/VideoInfo.sql
src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.xml
src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoInfoModel.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs

Displaying video thumbnail.
Adding the thumbnail column
Displaying videos generated thumbnail
Solves Github Issue #233

Adding Thumbnail column

---

src/FairPlayTubeSln/FairPlayTube/FairPlayTube.csproj
src/FairPlayTubeSln/FairPlayTube/Startup.cs

Enabling support for InMemoryDatabase
Solves Github Issue #188

Adding support for InMemoryDatabase

---

src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs

it was created the SearchVideosByPesonNameAsync method in the VideoService class
https://github.com/efonsecab/FairPlayTube/issues/186

SearchVideosByPerson method VideoService class

---

src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/VideoControllerTests.cs
src/FairPlayTubeSln/FairPlayTube.Tests/FairPlayTube.Tests.csproj
src/FairPlayTubeSln/FairPlayTube.Tests/TestsBase.cs
src/FairPlayTubeSln/FairPlayTube.Tests/appsettings.json

Making Tests project use configured server database. Defaulting to InMemoryDatabase
Solves Github Issue #241

Make tests use in memory database

---

src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/AzureVideoIndexerControllerTests.cs
src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/UserControllerTests.cs
src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/UserProfileControllerTests.cs
src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/VideoControllerTests.cs
src/FairPlayTubeSln/FairPlayTube.Tests/FairPlayTube.Tests.csproj
src/FairPlayTubeSln/FairPlayTube.Tests/VisitorTrackingControllerTests.cs

Adding tests placeholders
Solves Github Issue #246

Adding tests placeholders

---

src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/List.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/Program.cs
src/FairPlayTubeSln/FairPlayTube.ClientServices/UserClientService.cs
src/FairPlayTubeSln/FairPlayTube.ClientServices/UserProfileClientService.cs
src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/UserControllerTests.cs
src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/VideoControllerTests.cs
src/FairPlayTubeSln/FairPlayTube.Tests/FairPlayTube.Tests.csproj
src/FairPlayTubeSln/FairPlayTube.Tests/TestsBase.cs

Converted tests to use ClientServices instead of direct requests
Solves Github Issue #248

Converting tests to use ClientServices

---

src/FairPlayTubeSln/FairPlayTube.ClientServices/UserClientService.cs
src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/UserControllerTests.cs

Adding "InviteUserTest"
Solves Github Issue #250

Adding "InviteUserTest" automated test

---

src/FairPlayTubeSln/FairPlayTube.Client/CustomComponents/Upload/FileUpload.razor
src/FairPlayTubeSln/FairPlayTube.Client/CustomComponents/Upload/FileUpload.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/CustomValidators/UploadVideoValidator.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Upload.razor
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Upload.razor.cs
src/FairPlayTubeSln/FairPlayTube.Common/Configuration/DataStorageConfiguration.cs
src/FairPlayTubeSln/FairPlayTube.Controllers/FairPlayTube.Controllers.xml
src/FairPlayTubeSln/FairPlayTube.Controllers/FilesaveController.cs
src/FairPlayTubeSln/FairPlayTube.Controllers/VideoController.cs
src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.xml
src/FairPlayTubeSln/FairPlayTube.Models/FileUpload/UploadResult.cs
src/FairPlayTubeSln/FairPlayTube.Models/Video/UploadVideoModel.cs
src/FairPlayTubeSln/FairPlayTube.Services/FairPlayTube.Services.csproj
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
src/FairPlayTubeSln/FairPlayTubeSln.sln

Modifying system to allow multiple upload modes.
Creating the upload component
Solves Github Issue #265

Enabling file upload component

---

src/FairPlayTubeSln/FairPlayTube.Client/CustomComponents/Upload/FileUpload.razor.cs
src/FairPlayTubeSln/FairPlayTube.Controllers/FilesaveController.cs
src/FairPlayTubeSln/FairPlayTube.Models/CustomHttpResponse/ProblemHttpResponse.cs
src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.xml
src/FairPlayTubeSln/FairPlayTube.Services/FairPlayTube.Services.csproj
src/FairPlayTubeSln/FairPlayTube/Startup.cs

Solving issue with large files
Solves Github Issue #266

Fixed issue with large file uploads

---

src/FairPlayTubeSln/FairPlayTube.DataAccess/Data/FairplaytubeDatabaseContext.cs
src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/VideoIndexStatus.sql
src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/VideoControllerTests.cs
src/FairPlayTubeSln/FairPlayTube/Startup.cs

Implementing "GetMyPendingVideosQueueTest"
Solves Github Issue #254

Implementing "GetMyPendingVideosQueueTest" test

---

src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/VideoControllerTests.cs

Implemnting "GetPersonsTest"
Solves Github Issue #255

Adding get persons test

---

src/FairPlayTubeSln/FairPlayTube.DataAccess/Data/FairplaytubeDatabaseContext.cs
src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/VideoVisibility.sql
src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/VideoControllerTests.cs
src/FairPlayTubeSln/FairPlayTube/Startup.cs

Implementing "GetPublicProcessedVideosTest"
Solves Github Issue #256

Implementing "GetPublicProcessedVideosTest"

---

src/FairPlayTubeSln/FairPlayTube.Client/FairPlayTube.Client.csproj
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Public/Videos/Details.razor
src/FairPlayTubeSln/FairPlayTube.Client/_Imports.razor
src/FairPlayTubeSln/FairPlayTube.Client/wwwroot/Index.Development.html
src/FairPlayTubeSln/FairPlayTube.Components/FairPlayTube.Components.csproj
src/FairPlayTubeSln/FairPlayTube.Components/Videos/Video.razor
src/FairPlayTubeSln/FairPlayTube.Components/Videos/Video.razor.cs
src/FairPlayTubeSln/FairPlayTube.Components/_Imports.razor

Adding the Twitter Share Button to video's details
Solves Github Issue #281

Adding Twitter Shre Button

---

src/FairPlayTubeSln/FairPlayTube.DataAccess/Data/FairplaytubeDatabaseContext.cs
src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoInfo.cs
src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoInfo.partial.cs
src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/VideoInfo.sql

Adding the missing auditing columns and the corresponding partial class
Solves Github Issue #285

Adding missing auditing columns

---

src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.xml
src/FairPlayTubeSln/FairPlayTube.Models/UserAudience/UserFollowerModel.cs
src/FairPlayTubeSln/FairPlayTube.Services/UserService.cs

Implementing the "AddUserFollowerAsync" method
Solves Github Issue #297

Implementing the AddUserFollowerAsync method

---

src/FairPlayTubeSln/FairPlayTube.ClientServices/UserClientService.cs
src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
src/FairPlayTubeSln/FairPlayTube.Controllers/FairPlayTube.Controllers.xml
src/FairPlayTubeSln/FairPlayTube.Controllers/UserController.cs
src/FairPlayTubeSln/FairPlayTube.Services/UserService.cs
src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/UserControllerTests.cs
src/FairPlayTubeSln/FairPlayTube/Startup.cs

Implementing the "AddUserFollower" endpoint

---

src/FairPlayTubeSln/FairPlayTube.Client/CustomProviders/VideoEditAccessTokenProvider.cs
src/FairPlayTubeSln/FairPlayTube.Client/Program.cs
src/FairPlayTubeSln/FairPlayTube.Common/Interfaces/IVideoEditAccessTokenProvider.cs
src/FairPlayTubeSln/FairPlayTube.Components/FairPlayTube.Components.csproj
src/FairPlayTubeSln/FairPlayTube.Components/Videos/Video.razor
src/FairPlayTubeSln/FairPlayTube.Components/Videos/Video.razor.cs
src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor.cs

Removing dependency on ClientServices project
Solves Github Issue #304

Create i video edit access token provider

---

src/FairPlayTubeSln/FairPlayTube.Controllers/VideoController.cs
src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/VideoControllerTests.cs

It was created the endpoint to search videos by person name, using the method created in the following issue: https://github.com/efonsecab/FairPlayTube/issues/186
https://github.com/efonsecab/FairPlayTube/issues/187

it was created the endpoint to search videos by person name

---

src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/MyVideos.razor
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/MyVideos.razor.cs
src/FairPlayTubeSln/FairPlayTube.ClientServices/VideoClientService.cs
src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
src/FairPlayTubeSln/FairPlayTube.Common/Global/Enums/VideoIndexStatus.cs
src/FairPlayTubeSln/FairPlayTube.Components/Videos/Video.razor
src/FairPlayTubeSln/FairPlayTube.Components/Videos/Video.razor.cs
src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor
src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor.cs
src/FairPlayTubeSln/FairPlayTube.Database/Scripts/PostDeployment/Script.PostDeployment.sql
src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.xml
src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoInfoModel.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
src/FairPlayTubeSln/FairPlayTube/AutoMapperProfiles/GlobalMappingProfile.cs

Add ability to delete owned videos
Solves Github Issue #37

Add ability to delete owned videos

---

src/FairPlayTubeSln/FairPlayTube.Controllers/AzureVideoIndexerController.cs
src/FairPlayTubeSln/FairPlayTube.Services/BackgroundServices/VideoIndexStatusService.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs

it was centrelize the process to mark a video as Processed
https://github.com/efonsecab/FairPlayTube/issues/163

it was summed up the process to mark a video as processed

---

src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/List.razor
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/List.razor.cs
src/FairPlayTubeSln/FairPlayTube.Components/Notifications/MessageSender.razor
src/FairPlayTubeSln/FairPlayTube.Components/Notifications/MessageSender.razor.cs
src/FairPlayTubeSln/FairPlayTube.Models/UserMessage/UserMessageModel.cs

Allow Send Message On Users.
Depends on #211
Solves Github Issue #217

Allow Send Message On Users

---

src/FairPlayTubeSln/FairPlayTube.Client/Shared/MainLayout.razor

it was added a footer fixed for Desktop and Mobile version as well
https://github.com/efonsecab/FairPlayTube/issues/319

it was added the fixed footer

---

src/FairPlayTubeSln/FairPlayTube.Controllers/FairPlayTube.Controllers.xml
src/FairPlayTubeSln/FairPlayTube.Controllers/VideoController.cs
src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.xml
src/FairPlayTubeSln/FairPlayTube.Models/Video/ProjectModel.cs
src/FairPlayTubeSln/FairPlayTube.Services/FairPlayTube.Services.csproj
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs

Adding ability to create custom rendered videos
Solves Github Issue #322

Adding ability to create custom rendered videos

---

src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.xml
src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoPlaylistModel.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoPlaylistService.cs
src/FairPlayTubeSln/FairPlayTube/Startup.cs

Adding VideoPlaylist service
Solves Github Issue #317

Adding VideoPlaylist service

---

src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs

Adding DownloadVideoAsync to VideoService
Solves Github Issue #288

Adding DownloadVideoAsync to VideoService

---

src/FairPlayTubeSln/FairPlayTube.Controllers/FairPlayTube.Controllers.xml
src/FairPlayTubeSln/FairPlayTube.Controllers/VideoController.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/VideoControllerTests.cs

Adding DownloadVideo to VideoController
Solves Github Issue #288

Adding DownloadVideo to Videocontroller

---

src/FairPlayTubeSln/FairPlayTube.Client/FairPlayTube.Client.csproj
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Index.razor
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Index.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/wwwroot/Index.Development.html
src/FairPlayTubeSln/FairPlayTube.Client/wwwroot/index.html
src/FairPlayTubeSln/FairPlayTube.Client/wwwroot/js/files/fileDownloader.js
src/FairPlayTubeSln/FairPlayTube.ClientServices/VideoClientService.cs
src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
src/FairPlayTubeSln/FairPlayTube.Components/Videos/Video.razor
src/FairPlayTubeSln/FairPlayTube.Components/Videos/Video.razor.cs
src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor
src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor.cs
src/FairPlayTubeSln/FairPlayTube.Controllers/VideoController.cs
src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.xml
src/FairPlayTubeSln/FairPlayTube.Models/Video/DownloadVideoModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoInfoModel.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs

Adding "DownloadVideo" to "VideoClientService"
Solves Github Issue #328

Adding "DownloadVideo" To VideoClientService

---

src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/UserInvitation.cs
src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/UserInvitation.sql

Adding InviteCode
Solves Github Issue #330

Adding InviteCode and unique indexes

---

src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Home.razor
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Home.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/List.razor
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/List.razor.cs
src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
src/FairPlayTubeSln/FairPlayTube.Controllers/FairPlayTube.Controllers.xml
src/FairPlayTubeSln/FairPlayTube.Controllers/UserController.cs
src/FairPlayTubeSln/FairPlayTube.Services/UserService.cs

Adding draft for inviting user home page
Adding InviteUser to service.
Adding draft page for inviting user home page
Solves Github Issue #332

Adding invite user to UserService.

---

src/FairPlayTubeSln/FairPlayTube.Client/Pages/Index.razor
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Index.razor.cs
src/FairPlayTubeSln/FairPlayTube.ClientServices/VideoClientService.cs
src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
src/FairPlayTubeSln/FairPlayTube.Components/Videos/Video.razor
src/FairPlayTubeSln/FairPlayTube.Components/Videos/Video.razor.cs
src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor
src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor.cs
src/FairPlayTubeSln/FairPlayTube.Controllers/FairPlayTube.Controllers.xml
src/FairPlayTubeSln/FairPlayTube.Controllers/VideoController.cs
src/FairPlayTubeSln/FairPlayTube.DataAccess/Data/FairplaytubeDatabaseContext.cs
src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/VideoAccessTransaction.sql
src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.xml
src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoInfoModel.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs

Completing functionality to allow users to Buy access to a selected video.
Solves Github Issue #336

Completing functionality to buy video access

---

src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/InviteUser.razor
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/InviteUser.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/Shared/NavMenu.razor
src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs

Adding users invitation page
Solves Github Issue #338

Adding user invitation page

---

src/FairPlayTubeSln/FairPlayTube.Client/Program.cs
src/FairPlayTubeSln/FairPlayTube.Client/Shared/CultureSelector.razor
src/FairPlayTubeSln/FairPlayTube.Client/Shared/CultureSelector.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/Shared/MainLayout.razor
src/FairPlayTubeSln/FairPlayTube.Client/WebAssemblyHostExtension.cs
src/FairPlayTubeSln/FairPlayTube.Client/wwwroot/Index.Development.html
src/FairPlayTubeSln/FairPlayTube.Client/wwwroot/index.html
src/FairPlayTubeSln/FairPlayTube.Controllers/LocalizationController.cs
src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/Resource.sql
src/FairPlayTubeSln/FairPlayTube.Services/FairPlayTube.Services.csproj
src/FairPlayTubeSln/FairPlayTube.Services/TranslationService.cs
src/FairPlayTubeSln/FairPlayTube/FairPlayTube.xml
src/FairPlayTubeSln/FairPlayTube/Startup.cs
src/FairPlayTubeSln/FairPlayTube/Translations/BackgroundTranslationService.cs
src/FairPlayTubeSln/FairPlayTubeSln.sln

Adding base for automatic translations
Solves Github Issue #360

Adding base for automatic translations

---

src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/VideoPlaylists/MyPlayLists.razor
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/VideoPlaylists/MyPlayLists.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/Program.cs
src/FairPlayTubeSln/FairPlayTube.Client/Shared/NavMenu.razor
src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.csproj
src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.xml
src/FairPlayTubeSln/FairPlayTube.Models/Localization/UploadVideoModelLocalizer.cs
src/FairPlayTubeSln/FairPlayTube.Models/Validations/Video/UploadVideoModelLocalizer.cs
src/FairPlayTubeSln/FairPlayTube.Models/Video/UploadVideoModel.cs
src/FairPlayTubeSln/FairPlayTube/Translations/BackgroundTranslationService.cs

Adds the base system for Data Annotations validations
Solves Github Issue #366

Adding data annotations localization

---

.github/workflows/FairPlayTubeProd.yml
.github/workflows/codeql-analysis.yml
src/FairPlayTubeSln/FairPlayTube.Client/FairPlayTube.Client.csproj
src/FairPlayTubeSln/FairPlayTube.ClientServices/FairPlayTube.ClientServices.csproj
src/FairPlayTubeSln/FairPlayTube.Common/FairPlayTube.Common.csproj
src/FairPlayTubeSln/FairPlayTube.Common/Providers/IpAddressProvider.cs
src/FairPlayTubeSln/FairPlayTube.Components/FairPlayTube.Components.csproj
src/FairPlayTubeSln/FairPlayTube.Controllers/FairPlayTube.Controllers.csproj
src/FairPlayTubeSln/FairPlayTube.DataAccess/Data/FairplaytubeDatabaseContext.partial.cs
src/FairPlayTubeSln/FairPlayTube.DataAccess/FairPlayTube.DataAccess.csproj
src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.csproj
src/FairPlayTubeSln/FairPlayTube.Notifications/FairPlayTube.Notifications.csproj
src/FairPlayTubeSln/FairPlayTube.Services/FairPlayTube.Services.csproj
src/FairPlayTubeSln/FairPlayTube.Services/VisitorTrackingService.cs
src/FairPlayTubeSln/FairPlayTube.SystemConfigurator/FairPlayTube.SystemConfigurator.csproj
src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/VideoPlaylistControllerTests.cs
src/FairPlayTubeSln/FairPlayTube.Tests/FairPlayTube.Tests.csproj
src/FairPlayTubeSln/FairPlayTube.Translator.Windows/FairPlayTube.Translator.Windows.csproj
src/FairPlayTubeSln/FairPlayTube.VideoIndexer/FairPlayTube.VideoIndexer.csproj
src/FairPlayTubeSln/FairPlayTube/FairPlayTube.csproj

Upgrading to .NET 6
Solves Github Issue #373

Upgrading to .NET 6

---

src/FairPlayTubeSln/FairPlayTube.Client/CustomClaims/CustomAccountClaimsPrincipalFactory.cs
src/FairPlayTubeSln/FairPlayTube.Client/GlobalSuppressions.cs
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Public/Videos/VideosJobs.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Profile/MyFunds.razor
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Profile/MyFunds.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/MyVideos.razor.cs
src/FairPlayTubeSln/FairPlayTube.Controllers/FairPlayTube.Controllers.xml
src/FairPlayTubeSln/FairPlayTube.Controllers/FilesaveController.cs
src/FairPlayTubeSln/FairPlayTube.Controllers/UserYouTubeChannelController.cs
src/FairPlayTubeSln/FairPlayTube.Controllers/VideoController.cs
src/FairPlayTubeSln/FairPlayTube.Models/Paypal/PaypalCheckoutApprovedDataModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/Paypal/PaypalCheckoutApprovedDetailsModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/UserYouTubeChannel/YouTubeVideoModel.cs
src/FairPlayTubeSln/FairPlayTube.Services/BackgroundServices/VideoIndexStatusService.cs
src/FairPlayTubeSln/FairPlayTube.Services/GlobalSuppressions.cs
src/FairPlayTubeSln/FairPlayTube.Services/UserYouTubeChannelService.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoCommentService.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoJobApplicationService.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoPlaylistService.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
src/FairPlayTubeSln/FairPlayTube.Services/VisitorTrackingService.cs
src/FairPlayTubeSln/FairPlayTube.SystemConfigurator/Pages/Error.cshtml.cs
src/FairPlayTubeSln/FairPlayTube/FairPlayTube.xml
src/FairPlayTubeSln/FairPlayTube/GlobalSuppressions.cs
src/FairPlayTubeSln/FairPlayTube/Pages/Error.cshtml.cs
src/FairPlayTubeSln/FairPlayTube/Startup.cs

Applying more Code Analysis recommendations.
Solves Github Issue #371

Applying more recommendations from Code analysis

---

src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/ReceivedApplications.razor
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/ReceivedApplications.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/YouTube/Videos.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/Program.cs
src/FairPlayTubeSln/FairPlayTube.Client/Shared/NavMenu.razor
src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.xml
src/FairPlayTubeSln/FairPlayTube.Models/VideoJobApplications/Localizers/VideoJobApplicationLocalizer.cs
src/FairPlayTubeSln/FairPlayTube.Models/VideoJobApplications/VideoJobApplicationModel.cs
src/FairPlayTubeSln/FairPlayTube/AutoMapperProfiles/GlobalMappingProfile.cs

Creating the "ReceivedApplications" page
Solves Github Issue #378

Adding the "ReceivedApplications" page

---

src/FairPlayTubeSln/FairPlayTube.Client/Pages/Public/Videos/VideosJobs.razor
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Public/Videos/VideosJobs.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/ReceivedApplications.razor
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/ReceivedApplications.razor.cs
src/FairPlayTubeSln/FairPlayTube.ClientServices/VideoJobApplicationClientService.cs
src/FairPlayTubeSln/FairPlayTube.ClientServices/VideoJobClientService.cs
src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
src/FairPlayTubeSln/FairPlayTube.Controllers/FairPlayTube.Controllers.xml
src/FairPlayTubeSln/FairPlayTube.Controllers/VideoJobApplicationController.cs
src/FairPlayTubeSln/FairPlayTube.Controllers/VideoJobController.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoJobApplicationService.cs
src/FairPlayTubeSln/FairPlayTube.Services/VideoJobService.cs
src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/VideoJobControllerTests.cs

Implementing the video job approval flow
Solves Github Issue #382

Adding approval of applications

---

src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/UserProfile.cs
src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/UserProfile.sql

Adding "PaypalEmailAddress" column to "UserProfile" table
Solves Github Issue #386

Adding PaypalEmailAddress column to UserProfile table

---

src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Profile/MyProfile.razor
src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Profile/MyProfile.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/Program.cs
src/FairPlayTubeSln/FairPlayTube.Client/Shared/LoginDisplay.razor
src/FairPlayTubeSln/FairPlayTube.Client/Shared/MainLayout.razor
src/FairPlayTubeSln/FairPlayTube.Common/CustomHelpers/DisplayHelper.cs
src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/UserProfile.cs
src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/UserProfile.sql
src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.xml
src/FairPlayTubeSln/FairPlayTube.Models/UserProfile/Localizers/UpdateUserProfileModelLocalizer.cs
src/FairPlayTubeSln/FairPlayTube.Models/UserProfile/UpdateUserProfileModel.cs

Addng base UI for Users Profile
Solves Github Issue #388

Adding my profile page

---

src/FairPlayTubeSln/FairPlayTube.Common/Global/Enums/UserRequestType.cs
src/FairPlayTubeSln/FairPlayTube.Common/Interfaces/ICurrentUserProvider.cs
src/FairPlayTubeSln/FairPlayTube.DataAccess/Data/FairplaytubeDatabaseContext.cs
src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/ApplicationUser.cs
src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/UserRequest.cs
src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/UserRequest.partial.cs
src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.refactorlog
src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/UserRequest.sql
src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.xml
src/FairPlayTubeSln/FairPlayTube.Models/UsersRequests/CreateUserRequestModel.cs
src/FairPlayTubeSln/FairPlayTube.Services/UserRequestService.cs
src/FairPlayTubeSln/FairPlayTube/CustomProviders/CurrentUserProvider.cs
src/FairPlayTubeSln/FairPlayTube/FairPlayTube.xml

Implementing AddUserRequestAsync
Adding UserRequestService.
Implementing AddUserRequestAsync
Solves Github Issue #394

Adding UserRequestService

---

src/FairPlayTubeSln/FairPlayTube.Client/FairPlayTube.Client.csproj
src/FairPlayTubeSln/FairPlayTube.Client/Program.cs
src/FairPlayTubeSln/FairPlayTube.Controllers/FairPlayTube.Controllers.xml
src/FairPlayTubeSln/FairPlayTube.Controllers/UserRequestController.cs
src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/UserRequest.cs
src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/UserRequest.sql
src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.xml
src/FairPlayTubeSln/FairPlayTube.Models/UserProfile/Localizers/UpdateUserProfileModelLocalizer.cs
src/FairPlayTubeSln/FairPlayTube.Models/UsersRequests/CreateUserRequestModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/UsersRequests/Localizers/CreateUserRequestModelLocalizer.cs
src/FairPlayTubeSln/FairPlayTube.Services/UserRequestService.cs
src/FairPlayTubeSln/FairPlayTube.SharedConfiguration/FairPlayTube.SharedConfiguration.csproj
src/FairPlayTubeSln/FairPlayTube.SharedConfiguration/ModelsLocalizationSetup.cs
src/FairPlayTubeSln/FairPlayTube.Tests/TestsBase.cs
src/FairPlayTubeSln/FairPlayTube/Program.cs
src/FairPlayTubeSln/FairPlayTube/Startup.cs
src/FairPlayTubeSln/FairPlayTubeSln.sln

Adding the UserRequestController
Solves Github Issue #396

Adding user request controller

---

src/FairPlayTubeSln/FairPlayTube.Client/CustomComponents/UsersRequests/UserRequest.razor
src/FairPlayTubeSln/FairPlayTube.Client/CustomComponents/UsersRequests/UserRequest.razor.cs
src/FairPlayTubeSln/FairPlayTube.Client/Program.cs
src/FairPlayTubeSln/FairPlayTube.Client/Shared/MainLayout.razor
src/FairPlayTubeSln/FairPlayTube.ClientServices/UserRequestClientService.cs
src/FairPlayTubeSln/FairPlayTube.Common/CustomHelpers/DisplayHelper.cs
src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
src/FairPlayTubeSln/FairPlayTube.Common/Global/Enums/UserRequestType.cs
src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.xml
src/FairPlayTubeSln/FairPlayTube.Models/UsersRequests/CreateUserRequestModel.cs
src/FairPlayTubeSln/FairPlayTube.Models/UsersRequests/Localizers/CreateUserRequestModelLocalizer.cs
src/FairPlayTubeSln/FairPlayTubeSln.sln

Adding ability to submit user requests from the UI
Solves Github Issue #398

Adding ability to submit user requests from the UI

---

src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs

Email all users when a video has been marked as processed
Solves Github Issue #401

Notify all users when new videos have been uploaded

---

src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs

Fixing incorrect user name on email body.
Enhancing email body content.
Solves Github Issue #401

Fixing email body

---

src/FairPlayTubeSln/FairPlayTube.Services/FairPlayTube.Services.csproj
src/FairPlayTubeSln/FairPlayTube.Services/VisitorTrackingService.cs
src/FairPlayTubeSln/FairPlayTube/Startup.cs

Migration to IpData
Solves Github Issue #404

Migrating to IpData

---

src/FairPlayTubeSln/FairPlayTube.Client/wwwroot/Index.Development.html
src/FairPlayTubeSln/FairPlayTube.Client/wwwroot/index.html

Blocking access to web app if an Ad Blocker is enabled
